version: '3.9'
services:
  hipush:
    container_name: hipush
    image: hipush.com/library/hipush
    volumes:
      - ./config/local.yaml:/local.yaml
      # If iOS push is enabled, mount the push certificate into the container, consistent with the iso key_path
#      - /xxx.p8:/config/key/AuthKey_xxx.p8
      # If Android push is enabled, mount the AccountKey.json into the container, consistent with the android key_path
#      - /xxx-adminsdk-atk43-5a6cdebc4e.json:/config/key/AccountKey.json
    command: -config /local.yaml
    ports:
      - "7070:7070"
