FROM golang:1.23.2-alpine AS builder

ARG TARGETARCH
ARG TARGETOS

ARG GOGCFLAGS
ARG GOLDFLAGS
ARG GOFLAGS

ARG BUILD_BRANCH
ARG BUILD_COMMIT
ARG BUILD_TIME

ENV BUILD_BRANCH=${BUILD_BRANCH}
ENV BUILD_COMMIT=${BUILD_COMMIT}
ENV BUILD_TIME=${BUILD_TIME}
ENV BUILD_GO_VERSION=1.23.2

RUN echo "Branch: ${BUILD_BRANCH}, Commit: ${BUILD_COMMIT}, Build Time: ${BUILD_TIME}, Go version: ${BUILD_GO_VERSION}"

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod tidy

COPY . .

RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} CGO_ENABLED=0 go build -gcflags "${GOGCFLAGS}" -ldflags "${GOLDFLAGS}" -a -o hipush ${GOFLAGS} ./cmd/hipush;

FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/hipush .

ENTRYPOINT ["./hipush"]