// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/cossteam/hipush/internal/handler"
	"github.com/cossteam/hipush/internal/server"
	"github.com/cossteam/hipush/pkg/config"
	"github.com/cossteam/hipush/pkg/log"
	"github.com/cossteam/hipush/pkg/provisioner"
	"github.com/cossteam/hipush/pkg/provisioner/initializer"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewWire(configConfig *config.Config, logger *log.Logger) (*gin.Engine, func(), error) {
	provisioners := provisioner.NewProvisioners(logger, configConfig)
	pushHandler := handler.NewPushHandler(logger, provisioners)
	handlerHandler := handler.NewHandler(logger, pushHandler)
	provisionerInitializer := initializer.NewPluginInitializer(provisioners)
	engine := server.NewServerHTTP(logger, handlerHandler, provisionerInitializer)
	return engine, func() {
	}, nil
}

// wire.go:

var ProvisionerSet = wire.NewSet(provisioner.NewProvisioners, initializer.NewPluginInitializer)

var ServerSet = wire.NewSet(server.NewServerHTTP)

var HandlerSet = wire.NewSet(handler.NewPushHandler, handler.NewHandler)
