// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /)
	HelloHipush(c *gin.Context)
	// 向指定设备发送推送消息
	// (POST /api/v1/platforms/{platform}/apps/{appName}/devices/{token}/message)
	PushMessage(c *gin.Context, platform string, appName string, token string, params PushMessageParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// HelloHipush operation middleware
func (siw *ServerInterfaceWrapper) HelloHipush(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HelloHipush(c)
}

// PushMessage operation middleware
func (siw *ServerInterfaceWrapper) PushMessage(c *gin.Context) {

	var err error

	// ------------- Path parameter "platform" -------------
	var platform string

	err = runtime.BindStyledParameterWithOptions("simple", "platform", c.Param("platform"), &platform, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "appName" -------------
	var appName string

	err = runtime.BindStyledParameterWithOptions("simple", "appName", c.Param("appName"), &appName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter appName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "token" -------------
	var token string

	err = runtime.BindStyledParameterWithOptions("simple", "token", c.Param("token"), &token, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter token: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PushMessageParams

	// ------------- Optional query parameter "dryRun" -------------

	err = runtime.BindQueryParameter("form", true, false, "dryRun", c.Request.URL.Query(), &params.DryRun)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dryRun: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "retry" -------------

	err = runtime.BindQueryParameter("form", true, false, "retry", c.Request.URL.Query(), &params.Retry)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter retry: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "retryInterval" -------------

	err = runtime.BindQueryParameter("form", true, false, "retryInterval", c.Request.URL.Query(), &params.RetryInterval)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter retryInterval: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PushMessage(c, platform, appName, token, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/", wrapper.HelloHipush)
	router.POST(options.BaseURL+"/api/v1/platforms/:platform/apps/:appName/devices/:token/message", wrapper.PushMessage)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xXX1MaSxb/KlO9+4gOau0++Jbd+3CtTbZSbvJ0TVUm0MrcDDOTmcGEa1GFrggaEOK/",
	"GCQqWVT2Jhe8Fa8XAc13SaZ7hie+wlZ3DwPCEN3sVlnWdNN9zu+c8zt/egEElLCqyFA2dDC5APRACIYF",
	"+vlXSQw8vRMwREUmyyDUA5qosiWwli5QsoHWyuZlod1MW1tls76O00lUyePzFF6sWvlldsYups1a/Ut8",
	"CfiAqikq1AwRUgW3kW392kD7L9ltKEfCYPIHoKhQvqOqwMe+AoY4LxpRZ/lQk8AjHzCiKgSTQDc0UZ4D",
	"PvBiZE4ZIZsj+lNRHVGoLkEaURVRNqAGJg0tAmM+4EobQOUYt7qJmnErv8x1TnIEYi7jQHwhhFWJaA4o",
	"4VFnNdo5+nchDMG3Y7svaEIYGlDTB9G13iyjtUOUXcLbp+1mGmWrZuPIbB624ht28mdUyZsXq3j7FGcq",
	"fUAXwFMYHQOTYF6QInAMxFx8ypMfYcD4L/A9nL57s9seTt/lUOEUvY33eyxkGKo+yfPPnz93PRdQwt/s",
	"sAFLYj5wD+q6MAen4bMI1A2C9jolHzzwMqFDaPTLLj5r4Nfnrddn7WbKbBxZJxtmrY4y2+Zlpt1c7TNp",
	"4s9+vwuCQJuDGkEREAw4p2jRr6gipEq9dzMLpVbIzkbarq6g1HvnWG9uuG6cujfgMaLyejL/UYOzYBL8",
	"ge9mP++kPt+b9+SmIhtQNr6C1aw1zMtNtJJAlYt+NHipjAureOfUyi+zC+1m2q7+jg+O8NY5Oz0ANigY",
	"wjCKMxK7FEfpBMq9b717i0o7BMqnIl6s4tQO3syYl4UbuO4j6/HOehx4MWZW0eCcpkTk4FBuU7PwbhXl",
	"jlGhjOpb1lYZlZZJ2FYzKHuKX5/j3SurVO+DQ1jqanyiKBIUqMfFgFdV7LJw7wofJl0PEMV0p5NdOLVj",
	"xxP2b8u4nuOmvrtlmvFE66hK82sgILJiiLPRB3R7ICzxvHVw5FB2/2W7mcbVLXS89DleYJDZgc/xt+1m",
	"+nO8YH1sWI0Dd9P6pT9rQJglKfBKHVUTFc27Prt0bO6iRMqqn1zvGiFxLgSIKVpYkIAPSMpz0ih6HMMO",
	"DBivDwl+Rx/O5qxSvXXwsd+OIJwVIpLhJdMQDQkOk4kPk613uwOZtHPa689BqV7snYa6qsg6HKx0ASXo",
	"AQBtZgh/185xfNE6XOzDMO5Rzm7fHryz2tGYX0aJ383Lzd70tv95adbq1r/rOLXD8tyuHluNFZbk/bn9",
	"PzSuDuGGgHPrFs7mzKs95h27eoZ31weClMqhtYP/Y8si/IOBCKH8P0h9ZsETVPFvkOaASGCGoBCkoZDJ",
	"gDEJ7kSMkKKJPwnUDFemcytGhIryrDJo7/eiGtFDHN6tmrU4/nCF18ut+CKzH118RFkyW7TieftT0q4e",
	"4fUjlP0Xyr2yVi9QJW9XrlApibKv3CtOeWdc7wi/c38K+MA81HSmc2zUP+onXCXTm6CKYBJM0C0fUAUj",
	"RO3lyb85SJsQITE1bCpIhEJJUphk4AOaQ3d6adzvZ0R3+5cBXxh8yAhL3UmXfHXDNxPx+ycC5AT9gmz9",
	"RAlGe9ehMbaiujmmnP3Cd35ylv03+a5oj/wlOXItHPanLbS3z/Xq4UiV//7Bvbtcq/hb6+07ci3mA7yg",
	"ivz8GK9KgjGraGGdX+h8xnhBVXV+QVBVMn/G+CCcFwNQ5xcM5SmUY3wP+1VF92j0bqhZ5BkRvsQXnU6X",
	"y1gnp2Q0ofHnqFQO5V6x7jiMFdfDeD+ih+65ZV/tGXR/GKiRlJMuG82rl+h4iZsBoqLPANL8uBkgyEFN",
	"EYMzgOmiSULI1E2RjncoaZ5FRA0GOw3ZixiionsV3IF60eMRUi/YfNCTRKTO0TNDgTlhuiWucJQ9hG5E",
	"xsJA1G/R3D5M2tUV68Nxu5miAWs3V91h05kx18mE5sJmAobCpkJuCVp4Ehgbn3gR/ek2wNlcZdbq3Hda",
	"dDoic7hcRM0s6RDHS3i/QH55THQ9JmRoJPBhsfVzupXIWJcVtJHG+8uoUWctk/UNs5Yxm3n7055dTKPK",
	"futNggWox7RnEahFu7YFqWLgacysIOkeQ5yHHYU4Kp20khm7uo0/FJ1nGjXBYXTpV/vsiGyeruDDC5yp",
	"kLyjJxlYdvdLfKnV2LUrJWK4n7OLZatUN2sZ99chRmjQoEsPGyYGBy0P/NUs/lBkWsyLl63XZ2T0oU8h",
	"8pffajdTnXdQ3jrZYIQyGwlUKHOPqfbHHCqdmPV1zs+RkbiwirdTNwCeIs1xns5rHsD/5AH8EeMg1I2/",
	"KMFoXwMQVFUSA7Ts8D/qbMruyv3ao6jv4ehVrI8XWZVzXzrsRYSyayhxbu3VUOJj7wv8eqbEbmxe347d",
	"HQI9UDtIWXlmwwudOSLhsEAeqMC7kPeUNCZVh9q8d73utn0OFzJorYjelIEPRDSp5zEiqOJoiB6kb5H5",
	"MRB7FPtPAAAA//8irp6GnBIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
